### ISSUE TITLE
Rolling a token leads to an error

### ISSUE THREAD

**Issue by HecticElectron** [jongrim/next-dice-roller#316]
On a Mac desktop, in Chrome, when I click "Add token", and then select the token icon that appears on screen, and then click the "Roll selected dice" button at the bottom of the page: The page blanks out (white background, even if I was in dark mode) and gives the on-screen message "An unexpected error has occurred."

In the inspector console, react_devtools_backend.js line 2430 errors out twice, both times with the error message: "TypeError: Cannot read property 'sides' of undefined."

I can reload the page and re-enter the room, but the history of dice rolled is gone, both in the on-screen icons and in the text history drawer that expands at right. I have not found another way of getting past the error and getting the page's app to work again.

**Comment by jongrim** [comment]
Thanks for reporting! I've merged and deployed the fix so you shouldn't hit this issue anymore. Do let me know if you come across it or anything else.

**Comment by HecticElectron** [comment]
Awesome! Thanks. :) It’s the best roller I’ve come across, so I’m eager to use it in more games.

Chris
